branch-defaults:
  proversity/production:
    environment: badgr
    group_suffix: null
global:
  application_name: badgr
  default_ec2_keyname: proversity-eu-west-1
  default_platform: Python
  default_region: eu-west-1
  profile: default
  sc: git
