branch-defaults:
  proversity/production:
    environment: badgr-server
    group_suffix: null
global:
  application_name: badgr
  default_ec2_keyname: proversity-eu-west-1
  default_platform: Python2.7
  default_region: eu-west-1
  sc: git
