branch-defaults:
  proversity/staging:
    environment: BadgrTest-env
    group_suffix: null
global:
  application_name: badgr test
  default_ec2_keyname: proversity-eu-west-1
  default_platform: Python2.7
  default_region: us-east-1
  sc: git
