version: 2
jobs:
  build_production:
    docker:
      - image: circleci/node:6.10
    working_directory: ~/badgr-server
    steps:
      - checkout
      - run:
          name: apt-get update
          command: 'sudo apt-get update -y'
      - run:
          name: apt-get install python dev
          command: |
            sudo apt-get install build-essential autoconf libtool pkg-config python-opengl python-imaging python-pyrex python-pyside.qtopengl idle-python2.7 qt4-dev-tools qt4-designer libqtgui4 libqtcore4 libqt4-xml libqt4-test libqt4-script libqt4-network libqt4-dbus python-qt4 python-qt4-gl libgle3 python-dev libssl-dev --fix-missing
      - run:
          name: install pip
          command: 'sudo apt-get -y install python-pip'
      - run:
          name: install aws eb cli
          command: 'sudo pip install awsebcli --upgrade'
      - deploy:
          name: Deploy to Elastic Beanstalk
          command: |
            eb deploy badgr-server
      

workflows:
  version: 2
  deploy:
    jobs:
      - build_production:
          filters:
            branches:
              only: proversity/production